# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a53c69d1dfed31025f33900cbec7ed6f6e3dc9cf9628b0bdeeedcf4e257ffe188a2b109d2d3f9c95cd69d711f40000a29c870984a54666730ee887afecf99c6d

test:
  secret_key_base: 41a50052b608423a116ea6fed1f4db04d732473a9cd67f8cedd4999cd04ed8100bc974d2f339500b1f3faa26740f0bbb28e47e257af88cfa9a42ea171e9fda50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
